name: goview
services:
  app:
    image: allape/goview:latest
    restart: unless-stopped
    networks:
      - internal
      - caddy
    volumes:
      - ./certs:/app/certs
      - ./preview:/preview
    environment:
      GOVIEW_UI_FOLDER: /app/ui/
      GOVIEW_TRUSTED_CERTS: /app/certs/root.crt
      GOVIEW_PREVIEW_FOLDER: /preview
      GOVIEW_DATABASE_DSN: "root:Root_123456@(database:3306)/goview?charset=utf8mb4&parseTime=true"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:8.3.0
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: "curl http://127.0.0.1:3306 > /dev/null && exit 0 || exit 1"
    environment:
      - MYSQL_ROOT_PASSWORD=Root_123456
      - MYSQL_DATABASE=goview
    volumes:
      - ./database:/var/lib/mysql
networks:
  caddy:
    external: true
    name: caddy
  internal:
    internal: true
